export class GeneralConsts {
  public static readonly DEFAULTS = {
    DEFAULT_HANDLE_SEARCH_FILTER: 500,
    DEFAULT_COVER_DELAY: 1300
  };

  public static readonly PATTERNS = {
    DATE_TIME_PATTERN: 'yyyy-MM-dd HH:mm:ss',
    BACKUP_DATE_PATTERN: 'yyyy-MM-dd_HH-mm-ss',
    DATE_PATTERN: 'yyyy-MM-dd',
    DATE_PATTERN_SMALL: 'yy-MM-dd',
    TIME_PATTERN: 'hh:mm:ss a',
    FULL_DATE_TIME: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
  };

  public static readonly KEYS = {
    PREFERENCE_NAME: 'SHARED_PREFS',

    LIBRARY: {
      DEFAULT_MANGA: -1,
      DEFAULT_BOOK: -2,
      ORIENTATION: 'LAST_ORIENTATION',
      MANGA_ORDER: 'MANGA_LIBRARY_ORDER',
      MANGA_LIBRARY_TYPE: 'MANGA_LAST_LIBRARY_TYPE',
      BOOK_ORDER: 'BOOK_LIBRARY_ORDER',
      BOOK_LIBRARY_TYPE: 'BOOK_LAST_LIBRARY_TYPE',
      HISTORY_TYPE: 'HISTORY_LAST_TYPE',
      HISTORY_STATISTICS_TYPE: 'HISTORY_STATISTICS_LAST_TYPE',
      LAST_LIBRARY: 'LAST_LIBRARY',
      LIBRARY_TYPE: 'LIBRARY_TYPE',
      LIBRARY_ID: 'LIBRARY_ID',
      LIBRARY_ARRAY_ID: 'LIBRARY_ARRAY_ID',
      CLEAR_LIBRARY_LIST: 'CLEAR_LIBRARY_LIST'
    },

    LIBRARIES: {
      MANGA_INDEX_LIBRARIES: 1000,
      BOOK_INDEX_LIBRARIES: 2000,
      NOTIFICATION_SOLICITED: 'NOTIFICATION_SOLICITED'
    },

    SUBTITLE: {
      FOLDER: 'SUBTITLE_FOLDER',
      LANGUAGE: 'SUBTITLE_LANGUAGE',
      TRANSLATE: 'SUBTITLE_TRANSLATE'
    },

    READER: {
      MANGA_READER_MODE: 'MANGA_READER_MODE',
      MANGA_PAGE_SCROLLING_MODE: 'MANGA_PAGE_SCROLLING_MODE',
      MANGA_PAGE_PAGINATION_TYPE: 'MANGA_PAGE_PAGINATION_TYPE',
      MANGA_SHOW_CLOCK_AND_BATTERY: 'MANGA_SHOW_CLOCK_AND_BATTERY',
      MANGA_USE_MAGNIFIER_TYPE: 'MANGA_USE_MAGNIFIER_TYPE',
      MANGA_KEEP_ZOOM_BETWEEN_PAGES: 'MANGA_KEEP_ZOOM_BETWEEN_PAGES',
      MANGA_PROCESS_VOCABULARY: 'MANGA_PROCESS_VOCABULARY',
      BOOK_PAGE_ALIGNMENT: 'BOOK_PAGE_ALIGNMENT',
      BOOK_PAGE_MARGIN: 'BOOK_PAGE_MARGIN',
      BOOK_PAGE_SPACING: 'BOOK_PAGE_SPACING',
      BOOK_PAGE_SCROLLING_MODE: 'BOOK_PAGE_SCROLLING_MODE',
      BOOK_PAGE_PAGINATION_TYPE: 'BOOK_PAGE_PAGINATION_TYPE',
      BOOK_PAGE_FONT_TYPE_NORMAL: 'BOOK_PAGE_FONT_TYPE_NORMAL',
      BOOK_PAGE_FONT_TYPE_JAPANESE: 'BOOK_PAGE_FONT_TYPE_JAPANESE',
      BOOK_PAGE_FONT_SIZE: 'BOOK_PAGE_FONT_SIZE',
      BOOK_PAGE_FONT_SIZE_DEFAULT: 12,
      BOOK_PROCESS_JAPANESE_TEXT: 'BOOK_PROCESS_JAPANESE_TEXT',
      BOOK_GENERATE_FURIGANA_ON_TEXT: 'BOOK_GENERATE_FURIGANA_ON_TEXT',
      BOOK_FONT_JAPANESE_STYLE: 'BOOK_FONT_JAPANESE_STYLE',
      BOOK_PROCESS_VOCABULARY: 'BOOK_PROCESS_VOCABULARY',
      BOOK_READER_TTS_VOICE_NORMAL: 'BOOK_READER_TTS_VOICE_NORMAL',
      BOOK_READER_TTS_VOICE_JAPANESE: 'BOOK_READER_TTS_VOICE_JAPANESE',
      BOOK_READER_TTS_SPEED: 'BOOK_READER_TTS_SPEED',
      BOOK_READER_TTS_SPEED_DEFAULT: 0
    },

    TOUCH: {
      MANGA_TOUCH_DEMONSTRATION: 'MANGA_TOUCH_DEMONSTRATION',
      BOOK_TOUCH_DEMONSTRATION: 'BOOK_TOUCH_DEMONSTRATION',
      MANGA_TOP: 'MANGA_TOUCH_TOP',
      MANGA_TOP_RIGHT: 'MANGA_TOUCH_TOP_RIGHT',
      MANGA_TOP_LEFT: 'MANGA_TOUCH_TOP_LEFT',
      MANGA_RIGHT: 'MANGA_TOUCH_RIGHT',
      MANGA_LEFT: 'MANGA_TOUCH_LEFT',
      MANGA_BOTTOM: 'MANGA_TOUCH_BOTTOM',
      MANGA_BOTTOM_RIGHT: 'MANGA_TOUCH_BOTTOM_RIGHT',
      MANGA_BOTTOM_LEFT: 'MANGA_TOUCH_BOTTOM_LEFT',
      BOOK_TOP: 'BOOK_TOUCH_TOP',
      BOOK_TOP_RIGHT: 'BOOK_TOUCH_TOP_RIGHT',
      BOOK_TOP_LEFT: 'BOOK_TOUCH_TOP_LEFT',
      BOOK_RIGHT: 'BOOK_TOUCH_RIGHT',
      BOOK_LEFT: 'BOOK_TOUCH_LEFT',
      BOOK_BOTTOM: 'BOOK_TOUCH_BOTTOM',
      BOOK_BOTTOM_RIGHT: 'BOOK_TOUCH_BOTTOM_RIGHT',
      BOOK_BOTTOM_LEFT: 'BOOK_TOUCH_BOTTOM_LEFT'
    },

    SYSTEM: {
      LANGUAGE: 'SYSTEM_LANGUAGE',
      FORMAT_DATA: 'SYSTEM_FORMAT_DATA',
      FORMAT_DATA_SMALL: 'FORMAT_DATA_SMALL',
      SHARE_MARK_ENABLED: 'SHARE_MARK_ENABLED',
      SHARE_MARK_CLOUD: 'SHARE_MARK_CLOUD'
    },

    LLM: {
      ENABLED: 'LLM_ENABLED',
      MODEL_VERSION: 'LLM_MODEL_VERSION',
      MODEL_PATH: 'LLM_MODEL_PATH',
      MODEL_EXTRACTED: 'LLM_MODEL_EXTRACTED',
      MAX_CONTEXT_CHARS: 'LLM_MAX_CONTEXT_CHARS',
      MAX_HISTORY_CHARS: 'LLM_MAX_HISTORY_CHARS',
      MAX_BOOK_CHAPTERS: 'LLM_MAX_BOOK_CHAPTERS',
      MAX_MANGA_PAGES: 'LLM_MAX_MANGA_PAGES',
      TEMPERATURE: 'LLM_TEMPERATURE',
      SUMMARY_CACHE_PREFIX: 'LLM_SUMMARY_CACHE_',
      SELECTION_PREFIX: 'LLM_ASSISTANT_SELECTION_',
      PROVIDER: 'LLM_PROVIDER',
      OPENROUTER_API_KEY: 'LLM_OPENROUTER_API_KEY',
      BOOK_OPENROUTER_MODEL: 'LLM_BOOK_OPENROUTER_MODEL',
      BOOK_OPENROUTER_MODEL_SUMMARY: 'LLM_BOOK_OPENROUTER_MODEL_SUMMARY',
      MANGA_OPENROUTER_MODEL: 'LLM_MANGA_OPENROUTER_MODEL',
      DEFAULT_MAX_CONTEXT_CHARS: 12000,
      DEFAULT_MAX_HISTORY_CHARS: 600,
      DEFAULT_MAX_BOOK_CHAPTERS: 5,
      DEFAULT_MAX_MANGA_PAGES: 10,
      DEFAULT_BOOK_CHAPTERS: 3,
      DEFAULT_MANGA_RADIUS: 2,
      DEFAULT_TEMPERATURE: 80,
      DEFAULT_MODEL_VERSION: 'gemma3-1b-it-int4',
      DEFAULT_MODEL_FILENAME: 'gemma3-1b-it-int4.task',
      ASSET_MODEL_PATH: 'llm/gemma3-1b-it-int4.task',
      DEFAULT_PROVIDER: 'auto',
      DEFAULT_OPENROUTER_MODEL: 'openrouter/free'
    },

    THEME: {
      THEME_USED: 'THEME_USED',
      THEME_MODE: 'THEME_MODE',
      THEME_CHANGE: 'THEME_CHANGE',
      THEME_GLASSMORPHISM: 'THEME_GLASSMORPHISM',
      THEME_3D_COVER_IN_DETAIL: 'THEME_3D_COVER_IN_DETAIL'
    },

    SHARE_MARKS: {
      LAST_SYNC_MANGA: 'SHARE_MARKS_LAST_SYNC_MANGA',
      LAST_SYNC_BOOK: 'SHARE_MARKS_LAST_SYNC_BOOK'
    }
  };

  public static readonly CACHE_FOLDER = {
    TESSERACT: 'Tesseract',
    RAR: 'RarTemp',
    MANGA_COVERS: 'MangaCovers',
    BOOK_COVERS: 'BookCovers',
    BOOKS: 'Books',
    LINKED: 'Linked',
    IMAGE: 'Image',
    AUDIO: 'Audio',
    THREAD: 'Thread',
    LLM: 'llm'
  };

  public static readonly SHARE_MARKS = {
    MIN_DATE_TIME: '2000-01-01T00:00:00.000Z',
    PARSE_DATE_TIME: "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
    DATE_TIME: 'yyyyMMdd HHmmss',
    FILE_EXTENSION: '.json',
    FOLDER: 'BilingualReader',
    MANGA_FILE: 'MangaMarks',
    BOOK_FILE: 'BookMarks',
    MANGA_FILE_WITH_EXTENSION: 'MangaMarks.json',
    BOOK_FILE_WITH_EXTENSION: 'BookMarks.json'
  };
}
